# Site settings
title: Thiago Ganzarolli
email: mwkwqbwq
url: http://www.ganzarolli.uk
description: "Thiago Ganzarolli's personal website"
keywords: "your keywords, separated by commas"
skills: "MBA | Software Engineer | T[h]inker(er)"
meta_author: Ganzarolli Thiago

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ganzarolli-uk

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0096ff #80B3FF 
  primary-rgb: "0,150,255" #"128,179,255"
  secondary: aaaaaa #FD6E8A
  secondary-dark: 888888 #A2122F

# Footer settings
footer:
  copyright: Thiago Ganzarolli
  location: Based in
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/tganzarolli
  - title: facebook
    url: https://www.facebook.com/ThiagoGanzarolli
  - title: stack-overflow
    url: https://stackoverflow.com/users/287604/thiago-ganzarolli
  - title: linkedin
    url: https://www.linkedin.com/in/tganzarolli/
  - title: github
    url: http://github.com/tganzarolli

# Postal address (add as many lines as necessary)
address:
  - line: London

# Credits content
credits: 
  - line: 'Theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>' 
  - line: '<a href="https://flic.kr/p/63amB5">"55 - No Pop"</a> by <a href="https://www.flickr.com/photos/tourist_on_earth/">tourist_on_earth</a> licensed under <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>'
  - line: '<a href="https://commons.wikimedia.org/wiki/File:Da_Vinci%27s_Mona_Lisa_with_original_colors_approximation.jpg">Dianelos</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
